boot.o: boot.S multiboot.h x86_desc.h types.h idt_init.h
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_init.o: idt_init.c x86_desc.h types.h idt_init.h lib.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h rtc.h paging.h
lib.o: lib.c lib.h types.h
paging.o: paging.c x86_desc.h types.h idt_init.h lib.h i8259.h paging.h
rtc.o: rtc.c lib.h types.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
